### PR TITLE
Added questions

### PR DESCRIPTION
**Pull request by KejariwalAyush**

### CODE REVIEW

**Comment by KejariwalAyush** [comment]
add me as admin or collaberator

**Comment by MartyMiniac** [comment]
Dont add questions pdf. it will make the project file much larger. currently its just 18 Kbs. It would make it few Mb in size. While using git in CLI. Its a concern as time is important and internet speed is not always in our favour

**Comment by MartyMiniac** [comment]
As of adding you as a collaborator, I think you better fork the project and work with it. And required send a pull request. Actually my primary purpose of this not to showcase the answer but rather to maintain an easy access to my projects for me. So you can fork it but i cannot added you as a collaborator.

**Comment by KejariwalAyush** [comment]
ok fine no problem

**Pull request closed without merging**
